### ISSUE TITLE
problème d'installation libmavconn

### ISSUE THREAD

**Issue by jbporret** [simonernst/iROS_drone#2]
Bonjour,

Je tente d'installer les différents packages sur la VM donnée par le prof. Le catkin build semble échouer sur libmavconn. Je peux lancer gazebo mais pas communiquer en postant par exemple un /takeoff.
Ci-joint des photos de l'erreur. 
Merci & cordialement

Jean Baptiste

![image](https://user-images.githubusercontent.com/72705207/95687176-50ccd080-0c02-11eb-9aff-47b56ecb5f53.png)

![image](https://user-images.githubusercontent.com/72705207/95687187-62ae7380-0c02-11eb-9861-d453cb7b5852.png)

**Comment by simonernst** [comment]
Bonsoir, pour l'installation sur la VM, il faut passer sur la branche melodic du repo. 
Depuis le dossier iROS_drone 
```bash
git checkout melodic
```
Puis suivre la procédure d'installation dans le [README.md](https://github.com/simonernst/iROS_drone/tree/melodic) de la branche melodic

**Comment by jbporret** [comment]
Ok super ça fonctionne, merci !
